/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as RequireEmailRouteImport } from './routes/require-email'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as DesafioRouteImport } from './routes/desafio'
import { Route as BetaRouteImport } from './routes/beta'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StravaCallbackRouteImport } from './routes/strava.callback'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthenticatedTreinosRouteImport } from './routes/_authenticated/treinos'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedDietaRouteImport } from './routes/_authenticated/dieta'
import { Route as ApiStravaWebhookRouteImport } from './routes/api/strava/webhook'
import { Route as ApiStravaDisconnectRouteImport } from './routes/api/strava/disconnect'
import { Route as ApiPushSendRouteImport } from './routes/api/push/send'
import { Route as AuthenticatedProfileUsernameRouteImport } from './routes/_authenticated/profile.$username'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const RequireEmailRoute = RequireEmailRouteImport.update({
  id: '/require-email',
  path: '/require-email',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const DesafioRoute = DesafioRouteImport.update({
  id: '/desafio',
  path: '/desafio',
  getParentRoute: () => rootRouteImport,
} as any)
const BetaRoute = BetaRouteImport.update({
  id: '/beta',
  path: '/beta',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StravaCallbackRoute = StravaCallbackRouteImport.update({
  id: '/strava/callback',
  path: '/strava/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedTreinosRoute = AuthenticatedTreinosRouteImport.update({
  id: '/treinos',
  path: '/treinos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDietaRoute = AuthenticatedDietaRouteImport.update({
  id: '/dieta',
  path: '/dieta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiStravaWebhookRoute = ApiStravaWebhookRouteImport.update({
  id: '/api/strava/webhook',
  path: '/api/strava/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStravaDisconnectRoute = ApiStravaDisconnectRouteImport.update({
  id: '/api/strava/disconnect',
  path: '/api/strava/disconnect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushSendRoute = ApiPushSendRouteImport.update({
  id: '/api/push/send',
  path: '/api/push/send',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileUsernameRoute =
  AuthenticatedProfileUsernameRouteImport.update({
    id: '/profile/$username',
    path: '/profile/$username',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/beta': typeof BetaRoute
  '/desafio': typeof DesafioRoute
  '/privacidade': typeof PrivacidadeRoute
  '/require-email': typeof RequireEmailRoute
  '/setup': typeof SetupRoute
  '/dieta': typeof AuthenticatedDietaRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/treinos': typeof AuthenticatedTreinosRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/strava/callback': typeof StravaCallbackRoute
  '/profile/$username': typeof AuthenticatedProfileUsernameRoute
  '/api/push/send': typeof ApiPushSendRoute
  '/api/strava/disconnect': typeof ApiStravaDisconnectRoute
  '/api/strava/webhook': typeof ApiStravaWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/beta': typeof BetaRoute
  '/desafio': typeof DesafioRoute
  '/privacidade': typeof PrivacidadeRoute
  '/require-email': typeof RequireEmailRoute
  '/setup': typeof SetupRoute
  '/dieta': typeof AuthenticatedDietaRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/treinos': typeof AuthenticatedTreinosRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/strava/callback': typeof StravaCallbackRoute
  '/profile/$username': typeof AuthenticatedProfileUsernameRoute
  '/api/push/send': typeof ApiPushSendRoute
  '/api/strava/disconnect': typeof ApiStravaDisconnectRoute
  '/api/strava/webhook': typeof ApiStravaWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/beta': typeof BetaRoute
  '/desafio': typeof DesafioRoute
  '/privacidade': typeof PrivacidadeRoute
  '/require-email': typeof RequireEmailRoute
  '/setup': typeof SetupRoute
  '/_authenticated/dieta': typeof AuthenticatedDietaRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/treinos': typeof AuthenticatedTreinosRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/strava/callback': typeof StravaCallbackRoute
  '/_authenticated/profile/$username': typeof AuthenticatedProfileUsernameRoute
  '/api/push/send': typeof ApiPushSendRoute
  '/api/strava/disconnect': typeof ApiStravaDisconnectRoute
  '/api/strava/webhook': typeof ApiStravaWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/beta'
    | '/desafio'
    | '/privacidade'
    | '/require-email'
    | '/setup'
    | '/dieta'
    | '/feed'
    | '/search'
    | '/settings'
    | '/treinos'
    | '/auth/reset-password'
    | '/strava/callback'
    | '/profile/$username'
    | '/api/push/send'
    | '/api/strava/disconnect'
    | '/api/strava/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/beta'
    | '/desafio'
    | '/privacidade'
    | '/require-email'
    | '/setup'
    | '/dieta'
    | '/feed'
    | '/search'
    | '/settings'
    | '/treinos'
    | '/auth/reset-password'
    | '/strava/callback'
    | '/profile/$username'
    | '/api/push/send'
    | '/api/strava/disconnect'
    | '/api/strava/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/beta'
    | '/desafio'
    | '/privacidade'
    | '/require-email'
    | '/setup'
    | '/_authenticated/dieta'
    | '/_authenticated/feed'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/treinos'
    | '/auth/reset-password'
    | '/strava/callback'
    | '/_authenticated/profile/$username'
    | '/api/push/send'
    | '/api/strava/disconnect'
    | '/api/strava/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  BetaRoute: typeof BetaRoute
  DesafioRoute: typeof DesafioRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RequireEmailRoute: typeof RequireEmailRoute
  SetupRoute: typeof SetupRoute
  StravaCallbackRoute: typeof StravaCallbackRoute
  ApiPushSendRoute: typeof ApiPushSendRoute
  ApiStravaDisconnectRoute: typeof ApiStravaDisconnectRoute
  ApiStravaWebhookRoute: typeof ApiStravaWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/require-email': {
      id: '/require-email'
      path: '/require-email'
      fullPath: '/require-email'
      preLoaderRoute: typeof RequireEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desafio': {
      id: '/desafio'
      path: '/desafio'
      fullPath: '/desafio'
      preLoaderRoute: typeof DesafioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beta': {
      id: '/beta'
      path: '/beta'
      fullPath: '/beta'
      preLoaderRoute: typeof BetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strava/callback': {
      id: '/strava/callback'
      path: '/strava/callback'
      fullPath: '/strava/callback'
      preLoaderRoute: typeof StravaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/treinos': {
      id: '/_authenticated/treinos'
      path: '/treinos'
      fullPath: '/treinos'
      preLoaderRoute: typeof AuthenticatedTreinosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dieta': {
      id: '/_authenticated/dieta'
      path: '/dieta'
      fullPath: '/dieta'
      preLoaderRoute: typeof AuthenticatedDietaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/strava/webhook': {
      id: '/api/strava/webhook'
      path: '/api/strava/webhook'
      fullPath: '/api/strava/webhook'
      preLoaderRoute: typeof ApiStravaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/strava/disconnect': {
      id: '/api/strava/disconnect'
      path: '/api/strava/disconnect'
      fullPath: '/api/strava/disconnect'
      preLoaderRoute: typeof ApiStravaDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/send': {
      id: '/api/push/send'
      path: '/api/push/send'
      fullPath: '/api/push/send'
      preLoaderRoute: typeof ApiPushSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile/$username': {
      id: '/_authenticated/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof AuthenticatedProfileUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDietaRoute: typeof AuthenticatedDietaRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTreinosRoute: typeof AuthenticatedTreinosRoute
  AuthenticatedProfileUsernameRoute: typeof AuthenticatedProfileUsernameRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDietaRoute: AuthenticatedDietaRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTreinosRoute: AuthenticatedTreinosRoute,
  AuthenticatedProfileUsernameRoute: AuthenticatedProfileUsernameRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  BetaRoute: BetaRoute,
  DesafioRoute: DesafioRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RequireEmailRoute: RequireEmailRoute,
  SetupRoute: SetupRoute,
  StravaCallbackRoute: StravaCallbackRoute,
  ApiPushSendRoute: ApiPushSendRoute,
  ApiStravaDisconnectRoute: ApiStravaDisconnectRoute,
  ApiStravaWebhookRoute: ApiStravaWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
