/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StravaCallbackRouteImport } from './routes/strava.callback'
import { Route as AuthenticatedWorkoutsRouteImport } from './routes/_authenticated/workouts'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedDietRouteImport } from './routes/_authenticated/diet'
import { Route as ApiStravaWebhookRouteImport } from './routes/api/strava/webhook'
import { Route as AuthenticatedProfileUsernameRouteImport } from './routes/_authenticated/profile.$username'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StravaCallbackRoute = StravaCallbackRouteImport.update({
  id: '/strava/callback',
  path: '/strava/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkoutsRoute = AuthenticatedWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDietRoute = AuthenticatedDietRouteImport.update({
  id: '/diet',
  path: '/diet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiStravaWebhookRoute = ApiStravaWebhookRouteImport.update({
  id: '/api/strava/webhook',
  path: '/api/strava/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileUsernameRoute =
  AuthenticatedProfileUsernameRouteImport.update({
    id: '/profile/$username',
    path: '/profile/$username',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/diet': typeof AuthenticatedDietRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/workouts': typeof AuthenticatedWorkoutsRoute
  '/strava/callback': typeof StravaCallbackRoute
  '/profile/$username': typeof AuthenticatedProfileUsernameRoute
  '/api/strava/webhook': typeof ApiStravaWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/diet': typeof AuthenticatedDietRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/workouts': typeof AuthenticatedWorkoutsRoute
  '/strava/callback': typeof StravaCallbackRoute
  '/profile/$username': typeof AuthenticatedProfileUsernameRoute
  '/api/strava/webhook': typeof ApiStravaWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/_authenticated/diet': typeof AuthenticatedDietRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/workouts': typeof AuthenticatedWorkoutsRoute
  '/strava/callback': typeof StravaCallbackRoute
  '/_authenticated/profile/$username': typeof AuthenticatedProfileUsernameRoute
  '/api/strava/webhook': typeof ApiStravaWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/setup'
    | '/diet'
    | '/feed'
    | '/settings'
    | '/workouts'
    | '/strava/callback'
    | '/profile/$username'
    | '/api/strava/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/setup'
    | '/diet'
    | '/feed'
    | '/settings'
    | '/workouts'
    | '/strava/callback'
    | '/profile/$username'
    | '/api/strava/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/setup'
    | '/_authenticated/diet'
    | '/_authenticated/feed'
    | '/_authenticated/settings'
    | '/_authenticated/workouts'
    | '/strava/callback'
    | '/_authenticated/profile/$username'
    | '/api/strava/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SetupRoute: typeof SetupRoute
  StravaCallbackRoute: typeof StravaCallbackRoute
  ApiStravaWebhookRoute: typeof ApiStravaWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strava/callback': {
      id: '/strava/callback'
      path: '/strava/callback'
      fullPath: '/strava/callback'
      preLoaderRoute: typeof StravaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workouts': {
      id: '/_authenticated/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof AuthenticatedWorkoutsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diet': {
      id: '/_authenticated/diet'
      path: '/diet'
      fullPath: '/diet'
      preLoaderRoute: typeof AuthenticatedDietRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/strava/webhook': {
      id: '/api/strava/webhook'
      path: '/api/strava/webhook'
      fullPath: '/api/strava/webhook'
      preLoaderRoute: typeof ApiStravaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile/$username': {
      id: '/_authenticated/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof AuthenticatedProfileUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDietRoute: typeof AuthenticatedDietRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWorkoutsRoute: typeof AuthenticatedWorkoutsRoute
  AuthenticatedProfileUsernameRoute: typeof AuthenticatedProfileUsernameRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDietRoute: AuthenticatedDietRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWorkoutsRoute: AuthenticatedWorkoutsRoute,
  AuthenticatedProfileUsernameRoute: AuthenticatedProfileUsernameRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SetupRoute: SetupRoute,
  StravaCallbackRoute: StravaCallbackRoute,
  ApiStravaWebhookRoute: ApiStravaWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
